library(shiny)
library(shinydashboard)
library(plotly)
library(ggplot2)
library(pheatmap)
library(ggcorrplot)


home<- read.csv("homeChourly.csv")
Usage<-read.csv("HourlyUsage.csv")
appliance_yearly <-read.csv("appliance_yearly.csv")
appliance_monthly<-read.csv("appliance_monthly.csv")
kitchen_appliances<-read.csv("kitchen_appliances.csv")

dashboardPage(
  title='Understanding and Monitoring Energy Efficiency in SmartHomes', skin="green",
  
  dashboardHeader(title = "Understanding and Monitoring Energy Efficiency in SmartHomes",
                  titleWidth = 650),
  dashboardSidebar(
    sidebarMenu(
      sidebarSearchForm("searchText","buttonSearch","Search"),
    #menuItem("Data", tabName = "Dataset", icon = icon("database")),
    menuItem("Home Page", tabName = "Main", icon = icon("dashboard")),
    menuItem("Visualizations", tabName = "Viz", icon = icon("chart-line")),
      menuSubItem("Usage", tabName = "Liyan"),
     menuSubItem("Appliance", tabName = "Jack"),
      menuSubItem("Weather", tabName ="Aimee"),
      menuSubItem("Solar", tabName = "Sarah"),
    menuItem("Data", tabName = "Dataset", icon = icon("database"))
    )
  ),
  dashboardBody(
    tabItems(
      tabItem(tabName = "Dataset",
              fluidPage(
                
                titlePanel("Dataset"),
                
                mainPanel(
                  tabsetPanel(type="tab",
                              tabPanel("SmartHome Dataset", tableOutput("home")),
                              
                  ))
              )
              
              
      ),
      tabItem(tabName = "Main",
              fluidRow(
                  box(title="Amount of energy generated by Solar",background = "olive", solidHeader = T, plotlyOutput("histogram")),
                  box(title="Solar power per Month", background = "olive", solidHeader = T, plotlyOutput("SolarM"))
              ),
              
              fluidRow(
                  box(title="Mean Monthly Temp", background = "olive", solidHeader = T, plotOutput("temp")),
                  box(title="Yearly appliance usage", background = "olive", solidHeader = T, plotlyOutput("donut"))
                  
                )
            
      ),
      tabItem(tabName = "Aimee",
              fluidPage(
                
                # App title ----
                titlePanel("Energy generated by solar"),
                
                # Sidebar layout with input and output definitions ----
                sidebarLayout(
                  
                  # Sidebar panel for inputs ----
                  sidebarPanel(
                    
                    selectInput(inputId = "varA",
                                label="select the x-axis variable",
                                choices= list("Month")),
                    
                    selectInput(inputId = "varB",
                                label = "Select the Y-axis Variable:",
                                choices= list("cloudCover", "temperature","windSpeed", "precipProbability", "precipIntensity",
                                              "dewPoint", "pressure","solarGen"))
                    
                  ),
                  
                  # Main panel for displaying outputs ----
                  mainPanel(
                    
                    tabsetPanel(type='tabs',
                                tabPanel("Correlation", plotlyOutput(outputId = "Correlation")),
                                tabPanel("weatherScat", plotOutput(outputId="weatherScat")),
                                tabPanel("dewPoint", plotlyOutput(outputId = "dewPoint"))
                                
                                
                                
                    )
                    
                    
                  )
                )
              )
              ),
      tabItem(tabName = "Jack",
              fluidPage(titlePanel("Appliance usage by Month"),
                        sidebarLayout(
                          sidebarPanel(
                            selectInput(inputId = "varAppliance",
                                        label = "Select Appliance",
                                        choices= list("furnace", "kitchen", "dishwasher",	"microwave",	"fridge",	"homeOffice", 	"wineCellar", 	"garageDoor",	"barn",	"well",	"livingRoom")),
                            
                            selectInput(inputId = "varX",
                                        label = "Month",
                                        choices= list("monthNum"))
                          ),
                          mainPanel(
                            
                            tabsetPanel(type='tabs',
                                        tabPanel("interactiveAppliance", plotOutput(outputId = "interactiveAppliance")),
                                        tabPanel("Furnace", plotlyOutput(outputId = "Furnace")),
                                        tabPanel("Kitchen", plotlyOutput(outputId = "Kitchen"))
                                        
                            )
                          )
                        )
                        )
      ),
      tabItem(tabName = "Liyan",
              fluidPage(
                
                titlePanel("Energy consumption over time period"),
                
                # Sidebar panel for inputs ----
                mainPanel(
                  tabsetPanel(type="tab",
                              tabPanel("Daily", plotlyOutput("plot1", height=650, width= 1000)),
                              tabPanel("Monthly", plotlyOutput("plot2", height=650, width= 1000)),
                              tabPanel("Yearly", plotlyOutput("hist", height=650, width= 1000))
                  ))
              )
      ),
      tabItem(tabName = "Sarah",
              
              fluidPage(
                
                # App title ----
                titlePanel("Energy generated by solar"),
                
                # Sidebar layout with input and output definitions ----
                sidebarLayout(
                  
                  # Sidebar panel for inputs ----
                  sidebarPanel(
                    
                    selectInput(inputId = "varT",
                                label="select the x-axis variable",
                                choices= list("solarGen")),
                    
                    selectInput(inputId = "varW",
                                label = "Select the Y-axis Variable:",
                                choices= list("cloudCover","Month", "temperature","windSpeed"))
                    
                  ),
                  
                  # Main panel for displaying outputs ----
                  mainPanel(
                    tabsetPanel(type='tabs',
      
                    tabPanel("Scatter",plotOutput(outputId = "scatter")),
                    #tabPanel("Histogram",plotlyOutput(outputId = "histogram")),
                    tabPanel("monthScatter", plotlyOutput(outputId = "monthScatter", height = 750)),
                    tabPanel("Density", plotOutput(outputId = "density"))
                    )
                    
                  )
                )
              )
      )
      
    ),
  )
)